apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: openmct
  namespace: dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: openmct
    spec:
      serviceAccountName: appd-account
      containers:
        - name: openmct
          image: sashaz/openmct:v1
          command:
            - /bin/sh
            - -c
            - '/openmct/start.sh'
          env:
          - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: appd-key
                name: appd-secret
          envFrom:
          - configMapRef:
              name: node-config
          imagePullPolicy: Always
          volumeMounts:
          - name: appd-shim
            mountPath: /openmct/shim.js
            subPath: shim.js
          - name: appd-start
            mountPath: /openmct/start.sh
            subPath: start.sh
          ports:
          - containerPort: 8080
      restartPolicy: Always
      volumes:
      - configMap:
          name: appd-shim
        name: appd-shim
      - configMap:
          name: appd-start
          defaultMode: 511
        name: appd-start

---
apiVersion: v1
kind: Service
metadata:
  name: openmct
  namespace: dev
spec:
  selector:
    name: openmct
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  type: LoadBalancer
status:
  loadBalancer: {}
