apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app
spec:
  selector:
    matchLabels:
      name: dotnet-app
  replicas: 1
  template:
    metadata:
      labels:
        name: dotnet-app
    spec:
      serviceAccountName: appd-account
      initContainers:
      - name: appd-agent
        command:
          - cp
          - -ra
          - /opt/appdynamics/.
          - /opt/appd
        image: appdynamics/dotnet-core-agent:4.5.19
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /opt/appd
          name: appd-agent-repo
      containers:
      - name: dotnet-app
        image: mcr.microsoft.com/dotnet/samples:aspnetapp
        imagePullPolicy: IfNotPresent
        envFrom:
           - configMapRef:
              name: dotnet-config
        env:
          - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
            valueFrom:
                secretKeyRef:
                  name: appd-secret
                  key: appd-key
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /opt/appd
          name: appd-agent-repo
      restartPolicy: Always
      volumes:
        - name: appd-agent-repo
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-app
spec:
  selector:
    name: dotnet-app
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  type: NodePort
