#!/bin/sh
SSL_PARAM=""
if [ "${APPDYNAMICS_CONTROLLER_SSL_ENABLED}" == "true" ]; then
    SSL_PARAM+=" -s "
fi
$PHP_AGENT_HOME/install.sh ${SSL_PARAM} -a=${APPDYNAMICS_AGENT_ACCOUNT_NAME}@${APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY} ${APPDYNAMICS_CONTROLLER_HOST_NAME} ${APPDYNAMICS_CONTROLLER_PORT} ${APPDYNAMICS_AGENT_APPLICATION_NAME} ${APPDYNAMICS_AGENT_TIER_NAME} ${APPDYNAMICS_NODE_NAME} &&

php-fpm -F --pid /opt/bitnami/php/tmp/php-fpm.pid -y /opt/bitnami/php/etc/php-fpm.conf

