#!/bin/sh
SSL_PARAM=""
if [ "${APPDYNAMICS_CONTROLLER_SSL_ENABLED}" == "true" ]; then
    SSL_PARAM=" -s "
fi

PHP_AGENT_HOME=/opt/appdynamics/php-agent/

chmod -R 755 ${PHP_AGENT_HOME}
chmod 777 ${PHP_AGENT_HOME}/logs



${PHP_AGENT_HOME}/install.sh ${SSL_PARAM} -a=${APPDYNAMICS_AGENT_ACCOUNT_NAME}@${APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY} ${APPDYNAMICS_CONTROLLER_HOST_NAME} ${APPDYNAMICS_CONTROLLER_PORT} ${APPDYNAMICS_AGENT_APPLICATION_NAME} ${APPDYNAMICS_AGENT_TIER_NAME} ${APPDYNAMICS_NODE_NAME} &&

$APP_ENTRY_POINT


