resource "kubernetes_config_map" "ma_config" {
  metadata {
    name = "ma-config"
    namespace = kubernetes_namespace.custom_ns.metadata.0.name
  }

  data = {
    APPDYNAMICS_AGENT_ACCOUNT_NAME               = var.APPDYNAMICS_AGENT_ACCOUNT_NAME
    APPDYNAMICS_AGENT_ENABLE_CONTAINERIDASHOSTID = var.APPDYNAMICS_AGENT_ENABLE_CONTAINERIDASHOSTID
    APPDYNAMICS_AGENT_GLOBAL_ACCOUNT_NAME        = var.APPDYNAMICS_GLOBAL_ACCOUNT_NAME
    APPDYNAMICS_CONTROLLER_HOST_NAME = var.APPDYNAMICS_CONTROLLER_HOST_NAME
    APPDYNAMICS_CONTROLLER_PORT = var.APPDYNAMICS_CONTROLLER_PORT
    APPDYNAMICS_CONTROLLER_SSL_ENABLED = var.APPDYNAMICS_CONTROLLER_SSL_ENABLED
    APPDYNAMICS_DOCKER_ENABLED = var.APPDYNAMICS_DOCKER_ENABLED
    APPDYNAMICS_SIM_ENABLED = var.APPDYNAMICS_SIM_ENABLED
    EVENT_ENDPOINT = var.APPDYNAMICS_EVENTS_API_URL
  }
}

