#!/bin/sh

SSL_PARAM=""
if [ "${APPDYNAMICS_CONTROLLER_SSL_ENABLED}" = "true" ]; then
    SSL_PARAM=" -s "
fi

if [ ! -z "${PHP_INI_DIR}" ]; then
    PHP_INI_DIR=" -i=${PHP_INI_DIR}"
fi

PHP_AGENT_HOME=/opt/appdynamics/php-agent/

chmod -R 755 ${PHP_AGENT_HOME}
chmod 777 ${PHP_AGENT_HOME}/logs



${PHP_AGENT_HOME}/install.sh ${PHP_INI_DIR} ${SSL_PARAM} -a=${APPDYNAMICS_AGENT_ACCOUNT_NAME}@${APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY} ${APPDYNAMICS_CONTROLLER_HOST_NAME} ${APPDYNAMICS_CONTROLLER_PORT} ${APPDYNAMICS_AGENT_APPLICATION_NAME} ${APPDYNAMICS_AGENT_TIER_NAME} ${APPDYNAMICS_NODE_NAME} &&

$APP_ENTRY_POINT
